### ISSUE TITLE
Add GA tracking snippet

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/cast-website2.0#35]

**Comment by andrewMacmurray** [comment]
@suninthesky fyi I made a branch with all the google stuff on it so when you're ready to move the domain over to this one you can merge that branch in: (has the tag manager stuff too)

https://github.com/TechforgoodCAST/cast-website2.0/tree/google-analytics

**Comment by suninthesky** [comment]
Fab, thanks @andrewMacmurray!

**Comment by suninthesky** [comment]
Note: Site being replaced.
