### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by ivan-unfolds** [TechforgoodCAST/cast-website2.0#5]

**Comment by andrewMacmurray** [comment]
@eghale @suninthesky @ivanmauricio 
This is a first draft of the homepage, but any thoughts? Obviously we'll have to have a think of exactly what kind of copy and content we'd like on the page, but thought of maybe having some of the current opportunities as tiles (maybe we could have the homepage cycle through some of the current opportunities too)

Haven't really done much with the footer yet but will put some more love into it 😆 

![homepage](https://cloud.githubusercontent.com/assets/14013616/22465676/b8802a0e-e7b4-11e6-8808-edb18b8128ea.png)

**Comment by suninthesky** [comment]
@andrewMacmurray  Love it! Personally I wouldn't worry about a carousel in this sprint. Also some thoughts:

- I'd add a `background-color` to the 'find out more' link
- Titles for 'current opportunities' feel lost, perhaps a gradient or overlay with opacity might help
- Not against the lowercase headings, but I'd suggest limiting its use to perhaps the navbar, buttons/CTA's, and the footer

**Comment by andrewMacmurray** [comment]
thanks @suninthesky will make those changes
